name: Common Task Framework
on: push
jobs:
  ctf:
    runs-on: ubuntu-latest
    steps:
    - name: Docker log-in
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
    - name: Download hidden data
      run: docker pull islasgeci/hidden_camera_trap_photos:latest
