name: Common Task Framework
on: push
jobs:
  ctf:
    runs-on: ubuntu-latest
    steps:
    - name: Docker log-in
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
    - name: Download hidden data
      run: docker pull islasgeci/hidden_camera_trap_photos:latest
    - run: docker run --name hidden_photos islasgeci/hidden_camera_trap_photos:latest
    - run: docker cp hidden_photos:/camera_trap_photos .
    - name: Classify photos
      run: docker run --volume $PWD/camera_trap_photos:/workdir/data/raw/photos --volume $PWD:/workdir/data islasgeci/cat_recognition:latest make detection_with_yolo
    - name: Evalute classifier
      run: docker run islasgeci/referee_cat_recognition:latest make evaluate_classifier
